[package]
org = "ballerinax"
name = "h2.driver"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["H2"]
repository = "https://github.com/ballerina-platform/module-ballerinax-h2.driver"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[[platform.java11.dependency]]
path = "./lib/h2-2.2.220.jar"
